/* Main.c file generated by New Project wizard
 *
 * Created:   Wed Aug 9 2023
 * Processor: PIC16F876A
 * Compiler:  CCS for PIC
 */

#include <16F876A.h>
 #define REF_MIN   90.00
 #define REF_MAX 135.00

int main (void)
 { 
   // Write your code here
   while (1)
      ;
   return 0;
 }   
